### ISSUE TITLE
Image refresh for candlepin

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#11325]
Image refresh for candlepin
 * [ ] FAIL: image-refresh candlepin

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-j3s26.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-11325-20190307-000000/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-11325-20190307-000000/

**Comment by martinpitt** [comment]
Curious, I noticed the exact same thing on Friday when I was installing candlepin into a cloud instance:

```
ERROR:  Error installing rubygems-update:\n\trubygems-update requires Ruby version >= 2.3.0.\nERROR:  While executing gem ... (NoMethodError)\n    undefined method `version' for nil:NilClass", "stderr_lines": ["ERROR:  Error installing rubygems-update:", "\trubygems-update requires Ruby version 
```
My workaround was to edit out the rubygems update. But this seems to be "real", so needs to  be reported somewhere.

**Comment by martinpitt** [comment]
https://github.com/rubygems/rubygems/issues/2534 is the general upstream issue for that. Recent candlepin has fixed that in the Ansible scripts: https://github.com/candlepin/ansible-role-candlepin/commit/82ae5bf521f4103fe5314768145b63d94d750a47

However, in commit 06ff261d962d1d69545e30f99b0a5a9f66356616 we pinned candlepin to the old version as the Ansible scripts didn't work with the old 2.6 version from EPEL 7. However, now we have Ansible 2.7 there, so I'll try this again.

**Comment by martinpitt** [comment]
I can't make heads or  tail of this -- I filed https://bugzilla.redhat.com/show_bug.cgi?id=1688153

**Comment by martinpitt** [comment]
Fixed in #11387
