### PR TITLE
apps: Fix reading AppStream metadata config

### PR DESCRIPTION
**Pull request by martinpitt**
Commit 7bbf9168ac33 introduced a major bug: If the OS in os-release was
not found in the iteration, get_config() would return the whole map
instead of the default value. That crashed the page with
`TypeError: names.forEach is not a function`.

This is awkward to do correctly with .find(), especially due to
modifying `val` as a side effect; iterate over `os_list` the good old
`for` way instead.

This was hidden by the test's manifest override leaving
`appstream_config_packages` intact, so it was always taken from the real
underlying OS. Override it as well.

---

Broken out from PR #19281, as this is a release-blocker, and the former needs some more work.

### CODE REVIEW

**Comment by martinpitt** [comment]
[This revdeps failure](https://artifacts.dev.testing-farm.io/fe7ea728-1ebf-403b-b9ea-4ec10ca68e79/) is persistent now, it somehow got introduced with https://github.com/cockpit-project/cockpit-podman/pull/1301 . @jelly is looking into it.

**Comment by mvollmer** [comment]
Autsch!

**Comment by mvollmer** [comment]
Hmm, I can't get testOSMap to fail with the current code...

**Comment by mvollmer** [comment]
> Hmm, I can't get testOSMap to fail with the current code.

When get_config returns a object, it will be treated like a empty array (jay JavaScript), and nothing will crash (`{ foo: 12 }.length` is undefined).

I believe the crash only happens with the additional code in https://github.com/cockpit-project/cockpit/pull/19281.

So, this here is a fix for a clear bug, but it might not qualify as a release blocker.

**Review by mvollmer — APPROVED** [review]

**Comment by mvollmer** [comment]
> I believe the crash only happens with the additional code in #19281.

Also, I don't see how failing to override `appstream_config_packages` would hide the crash.
