### PR TITLE
systemd/services: Avoid time.clock_gettime_ns()

### PR DESCRIPTION
**Pull request by martinpitt**
This does not yet exist in Python 3.6 (on RHEL 8), thus causing a warning message and the root-only fallback. Use time.clock_gettime() instead, which was introduced in Python 3.3 already.

Change the Python code to return µs instead of ns, which simplifies the calculation.

---

This was a regression from #18466, but I didn't notice because we don't show errors from passed tests. In failed tests it [looks like this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18532-20230320-165624-d2a3bf0e-centos-8-stream-pybridge/log.html#302-2):

    AttributeError: module 'time' has no attribute 'clock_gettime_ns'

### CODE REVIEW

**Review by allisonkarlitskaya — APPROVED** [review]
happy bots, happy lis
